services:
  glossary-service:
    build:
      context: ./glossary-service
      dockerfile: Dockerfile
    container_name: glossary_service
    ports:
      - "8000:80"
    depends_on:
      postgres-db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://postgres:1234@postgres-db:5432/glossary-db

  storage-service:
    build:
      context: ./storage-service
      dockerfile: Dockerfile
    container_name: storage_service
    ports:
      - "8001:80"
    depends_on:
      postgres-db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://postgres:1234@postgres-db:5432/storage-db
      - GLOSSARY_SERVICE_URL=http://glossary-service

  order-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    ports:
      - "8002:80"
    depends_on:
      mongo-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      - MONGO_URI=mongodb://mongo-db:27017
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - STORAGE_SERVICE_URL=http://storage-service

  notification-service:
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    ports:
      - "8003:80"
    depends_on:
      mongo-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      - MONGO_URI=mongodb://mongo-db:27017
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/

  graphql-service:
    build:
      context: ./graphql-service
      dockerfile: Dockerfile
    ports:
      - "8004:80"
    depends_on:
      - glossary-service
      - order-service
    environment:
      - GLOSSARY_SERVICE_URL=http://glossary-service
      - ORDER_SERVICE_URL=http://order-service

  postgres-db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db_config/postgres/postgres_init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  mongo-db:
    image: mongo:6.0
    container_name: mongo-db
    hostname: mongo-db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 30s

volumes:
  postgres-data:
  mongo-data:
